"""
At this point, you may wonder what fundamentally distinguishes a lambda function bound
to a variable from a regular function with a single return line: under the surface almost nothing.
Let's verify how python sees a function built with a single return statement versus a function constructed
as an expression(lambda)

the dis module exposes functions to analyze Python bytecode generated byt the python compiler."""

import dis
add = lambda x, y: x + y
type(add)

dis.dis(add)

"""we can see that dis() expose a readable version of the bytecode allowing the
inspection of the low-level instructions that the python interpreter will use while executing the program."""

